dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://120.79.182.70:2181

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.182.70:3306/dc
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  elasticsearch:
    jest:
      uris: http://120.79.182.70:9200
  rabbitmq:
    host: 120.79.182.70
    virtual-host: /
    username: guest
    password: guest
    port: 5672
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: manual

#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 120.79.182.70:9300
#      repositories:
#        enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazyLoadingEnabled: false
    cacheEnabled: true
logging:
  level:
    com.dc.demo.dubbo: debug
server:
  port: 8081
  servlet:
    context-path: /consumer
log:
  path: logs/
  base: consumer
  size: 10MB
  level: info
  live: 1